blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

project17/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('social-auth/', include('social_django.urls', namespace='social')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^images/', include('images.urls', namespace='images', app_name='images')),
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published_date')
    author = models.ForeignKey(User, related_name='blog_posts')
    content = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-published_date',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.published_date.year,
                              self.published_date.strftime('%m'),
                              self.published_date.strftime('%d'),
                              self.slug]
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

    def __unicode__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from haystack.query import SearchQuerySet

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 3
    template_name = 'blog/post/post_list.html'

    def get_queryset(self):
        return Post.published.all()

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['section'] = 'blog'
        return context


@login_required
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             published_date__year=year,
                             published_date__month=month,
                             published_date__day=day)

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            # save the comment to the database
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form
    }

    # posts by similarity
    # post_tags_ids = post.tags.values_lists('id',flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published_date')[:4]

    return render(request, 'blog/post/post_detail.html', context)


@login_required
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recomends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n comments: {}'.format(post.title, post_url, cd['comments'])
            send_mail(subject, message, 'pedro.miguel@live.co.uk', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {'post': post, 'form': form, 'sent': sent}

    return render(request, 'blog/post/post_share.html', context)


def post_search(request):
    form = SearchForm()

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()

            # count total results
            total_results = results.count()
        return render(request,
                      'blog/post/main.html',
                      {'form': form,
                       'cd': cd,
                       'results': results,
                       'total_results': total_results})
    return render(request, 'blog/post/main.html', {'form': form})

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/main.html
{% extends "base.html" %}
{% load blog_tags %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/codehilite.css' %}">
{% endblock extra_css %}

{% block main %}
    <div id="main">
        <div id="content">
            <h1>Blog</h1>
            <div id="search">
                <form action="/blog/search/" method="get">
                    <input type="text" name="query">
                    <input type="submit" value="Search">
                </form>
            </div>

            {% if "query" in request.GET %}
                <h3>Posts containing "{{ cd.query }}"</h3>
                <p>Search returned {{ total_results }} result{{ total_results|pluralize }}</p>

                {% for result in results %}
                    {% with post=result.object %}
                        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                        {{ post.content|truncatewords:5 }}
                    {% endwith %}
                {% endfor %}
            {% else %}
                {% block content %}
                {% endblock content %}
            {% endif %}

        </div>
        <div id="sidebar">
            <h2>Menu</h2>
            <p>This blog has {% total_posts %} posts so far.</p>
            <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS Feed</a></p>
            <h3>Latest Posts</h3>
            {% show_latest_posts %}

            {% get_most_commented_posts as commented_posts %}
            {% if commented_posts %}
                <h3>Most commented posts.</h3>
                <ul>
                    {% for post in commented_posts %}
                        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock main %}

blog/templates/blog/post/post_detail.html
{% extends "blog/post/main.html" %}
{% load blog_tags %}

{% block title %}Blog {{ post.title }}{% endblock title %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <p class="date">Published {{ post.published_date }} by {{ post.author }}</p>
    {{ post.content|markdown }}
    <p><a href="{% url "blog:post_share" post.id %}">Share this code</a></p>

    <!-- <h3>Similar Posts</h3>
     for post in similar_posts
        <p><a href=" post.get_absolute_url "> post.title </a></p>
     empty
        <p>There are no similar posts yet</p>
     endfor -->

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.content|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h3>Your comment has been added.</h3>
    {% else %}
        <h3>Add new comment</h3>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/post_list.html
{% extends "blog/post/main.html" %}
{% load blog_tags %}

{% block title %}Blog Posts List{% endblock title %}

{% block content %}

{% for post in post_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    <p class="date">Published {{ post.published_date }} by {{ post.author }}</p>
    {{ post.content|markdown|truncatewords_html:30 }}
{% endfor %}

{% include "pagination.html" with page=page_obj %}

{% endblock content %}

blog/templates/blog/post/post_share.html
{% extends "blog/post/main.html" %}


{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent!</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock content %}