account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login, logout, logout_then_login,
                                       password_change, password_change_done,
                                       password_reset, password_reset_done,
                                       password_reset_confirm,
                                       password_reset_complete)

from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),

    # user editing
    url(r'^edit/$', views.edit, name='edit'),

    # registration urls
    url(r'^register/$', views.register, name='register'),

    # login & logout urls
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),

    # password urls
    url(r'^password-change/$', password_change, {'post_change_redirect': 'account:password_change_done'}, name='password_change'),

    url(r'^password-change/done/$', password_change_done, name='password_change_done'),

    url(r'^password-reset/$', password_reset, {'post_reset_redirect': 'account:password_reset_done'}, name='password_reset'),

    url(r'^password-reset/done/$', password_reset_done, name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, {'post_reset_redirect': 'account:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^password-reset/complete/$', password_reset_complete, name='password_reset_complete'),
]

blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

project17/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('social-auth/', include('social_django.urls', namespace='social')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^images/', include('images.urls', namespace='images', app_name='images')),
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Project17{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body>
    <div id="header">
        <span class="logo"><a href="{% url 'blog:post_list' %}">Project17</a></span>
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li {% if section == 'blog' %}class="selected"{% endif %}>
                        <a href="{% url 'blog:post_list' %}">Blog</a>
                    </li>
                    <li {% if section == 'dashboard' %}class="selected"{% endif %}>
                        <a href="{% url 'account:dashboard' %}">My Dashboard</a>
                    </li>
                    <li {% if section == 'images' %}class="selected"{% endif %}>
                        <a href="#">Images</a>
                    </li>
                    <li {% if section == 'people' %}class="selected"{% endif %}>
                        <a href="#">People</a>
                    </li>
                </ul>
            {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name }}, <a href="{% url 'account:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}">Login</a>
            {% endif %}
        </span>
    </div>
    {% block main %}
    {% endblock main %}
    <script src="{% static 'javascript/jquery/jquery-3.2.1.slim.min.js' %}">
        $(document).ready(function () {
            {% block domready %}
            {% endblock domready %}
        });
    </script>
</body>
</html>